### ISSUE TITLE
Equality check on properties to fail or pass the validation

### ISSUE THREAD

**Issue by yashwanthkalva** [json-schema-org/json-schema-vocabularies#38]
How do you write a validation, if you want it fail if two integer type properties are same, the values to these 2 properties will be either provided as input or has defaults. Please let me know.

**Comment by Relequestual** [comment]
It's not currently possible to do this. Sorry.
Someone would have to define a new vocabulary and dialect which used somthing like `$data`, but this has not yet happened.

You will need to write your own code to do this, or use a library that allows you to extend what JSON Schema can do.

**Comment by Relequestual** [comment]
Also, @yashwanthkalva, please do not spam our Github. I can see you posted the same message in two other locations. That is not OK.

**Comment by yashwanthkalva** [comment]
Hi @Relequestual It was not intentional, I think I overlooked that it belongs to same community, I was wandering all over the place for a solution to this problem/limitation is related to json-schema. I saw references from here to different json schema providers ajv and others, thought have posted there too. But looks like it was all to same community. Sorry for the inconvenience. Point noted.

**Comment by Relequestual** [comment]
If you don't need an interoperable solution, ajv might be your best bet.
